config/routes.rb
Rails.application.routes.draw do
    root to: 'grayscales#index'

    get '/thankyou', to: 'contact_form#show', as: 'thankyou'
    post '/create', to: 'contact_form#create', as: 'create'

    get '/blog', to: 'blog_posts#index', as: 'blog'
    get '/blog/:slug', to: 'blog_posts#show', as: 'blog_post'
end

app/models/admin.rb
class Admin < ActiveRecord::Base


  has_secure_password
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      validate: true
  attribute :email,     validate:  /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      attachment: true

  attribute :message
  attribute :nickname,  captcha:   true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject:  "Website Contact",
      to:  "jackschuss@gmail.com",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  def index
    @blog_posts = Ramble::BlogPost.all(sort_by: :written_on, desc: true)
  end

  def show
    @show_page = true

    @blog_post = Ramble::BlogPost.find_by_slug(params[:slug])
  rescue Ramble::BlogPost::NotFound
    redirect_to blog_path
  end

end

app/controllers/contact_form_controller.rb
class ContactFormController < ApplicationController
  layout 'grayscale'

  def create
    c = ContactForm.new(contact_form_params)

    if c.deliver
      redirect_to thankyou_path
      flash[:success] = "Thanks for reaching out! Jack will be in touch shortly."
    else
      render root_path
      flash[:error] ="Oops! Something went wrong. You can always send an email manually to j@jackschuss.com."
    end
  end

  def show
  end


  private

  def contact_form_params
    params.require(:contact_form).permit(:name, :email, :message)
  end
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ActionController::Base
  include Dashboard::SessionsHelper
  layout 'dashboard'

  protect_from_forgery with: :exception


  private

  def require_sign_in
    unless current_user
      redirect_to new_dashboard_session_path
    end
  end

end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < Dashboard::ApplicationController

  before_action :require_sign_in


  def new
    @post = Post.new
  end


  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end

  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      redirect_to posts_path
    else
      render @post
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end


end

app/controllers/dashboard/sessions_controller.rb
class Dashboard::SessionsController < ActionController::Base
  include Dashboard::SessionsHelper
  layout 'dashboard'

  def new
  end

  def create
    admin = Admin.find_by(username: params[:session][:username].downcase)

    if admin && admin.authenticate(params[:session][:password])
      create_session admin
      redirect_to new_dashboard_post_path
    else
      flash[:error] = 'Invalid Username/Password combination'
      render :new
    end
  end

  def destroy

    destroy_session(current_admin)
    redirect_to root_path

  end


end

app/controllers/grayscales_controller.rb
class GrayscalesController < ApplicationController
  layout "grayscale"
    def index
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'grayscale'

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/dashboard/session_helper.rb
module SessionsHelper
    def create_session(user)
        session[:user_id] = user.id
    end

    def destroy_session(user)
        session[:user_id] = nil
    end

    def current_user
        Admin.find_by(id: session[:user_id])
    end

end

app/helpers/dashboard/sessions_helper.rb
module Dashboard::SessionsHelper

    def create_session(user)
        session[:user_id] = user.id
    end

    def destroy_session(user)
        session[:user_id] = nil
    end

    def current_user
        Admin.find_by(id: session[:user_id])
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog_posts/_blog_post.html.erb
<article id="<%= blog_post.slug %>">
  <header>
    <h1 class="blog-post-title"><%= link_to blog_post.title, blog_post_path(blog_post.slug) %></h1>
    <em>Written on <%= blog_post.written_on %></em>
  </header>

  <p><%= blog_post.preview %></p>
</article>

app/views/blog_posts/_navigation.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <% if @show_page %>
        <a class="navbar-brand page-scroll" href="/blog" id="navbar-brand-header">
      <% else%>
        <a class="navbar-brand page-scroll" href="#page-top" id="navbar-brand-header">
      <% end %>
          <div class="picture-header">
            <i class="white-logo-picture"></i>
          </div>
          <div class="name-header">
            <span class="light">  Jack</span> Schuss
          </div>
          </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <a class="page-scroll" href="/">Home</a>
        </li>
        <% if @show_page %>
          <li>
            <a href="/blog">Posts</a>
          </li>
        <% end %>

      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/blog_posts/index.html.erb
<div class="blog-post-namespace">
  <%= render 'navigation' %>
  <div class="container">
  <% if @blog_posts.empty? %>
    <div class="center-text">
      <p>Nothing here! Come back later.</p>
    </div>
  <% end %>

  <% @blog_posts.each do |blog_post| %>
    <%= render partial: "blog_posts/blog_post.html.erb", locals: { blog_post: blog_post } %>
  <% end %>
  </div>
</div>

app/views/blog_posts/show.html.erb
<div class="blog-post-namespace">
  <%= render 'navigation' %>
  <div class="container">
    <div class="row">
      <div class="title">
        <%= @blog_post.title %>
      </div>

      <div class="written-on">
        <%= @blog_post.written_on %>
      </div>

    </div>
    <div class="row">
      <%= @blog_post.body.html_safe %>
    </div>
  </div>
</div>

app/views/contact_form/show.html.erb
<div class="thank-you-page">
  <div class="container">
    <div class="row">
      <div class="jumbotron">
      <h2 class="header">
        Thank you so much for reaching out. Jack will get in touch shortly.
        </h2>
      </div>
    </div>
  </div>
</div>

<script>
  (function(){
        setTimeout(function() {
                window.location='/'
                      }, 3000);
          })(); 
</script>

app/views/dashboard/posts/_form.html.erb
<%= form_for [:dashboard, @post] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <%= f.label :body %>
  <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  </br>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/dashboard/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <%= render partial: 'form', locals: {post: @post} %>
    </div>
  </div>
</div>

app/views/grayscales/_about.html.erb
<section id="about" class="container content-section text-center about-section">
    <div class="spacer-l"></div>
    <div class="row">
        <div class="col-sm-2 col-lg-2 col image-section-personal">
            <img class="personal-picture" alt="Jack" />
        </div>
        <div class="col-sm-4 col-md-6 col-lg-8 about-section-text">
            <h1>About Me</h2>
            <p>I'm a solution oriented software developer with an unique perspective on integrating business goals with programming objectives.</p>
            <p>My primary goal is to improve businesses in a clean, efficient, and effective manner.</p>
            <p>My driving value is helping people improve, and I love thinking of ways to benefit the end-user.</p>
        </div>
    </div>
</section>

app/views/grayscales/_contact.html.erb
<section id="contact" class="container content-section text-center contact-section-download">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 contact-section">
      <h1>Contact Jack</h1>
      <p>Feel free to get in touch with me for feedback, interesting articles, books, or opportunities!</p>
      <ul class="social-media">
        <li>
          <%= link_to "https://www.linkedin.com/in/jackschuss", target: "_blank" do %>
            <i class="fa fa-linkedin fa-3x"></i>
          <% end %>
        </li>
        <li>
          <%= link_to "https://github.com/yakschuss", target: "_blank" do %>
            <i class="fa fa-github fa-3x"></i>
          <% end %>
        </li>
        <li>
          <%= link_to "mailto:j@jackschuss.com", target: "_blank" do %>
            <i class="fa fa-envelope-o fa-3x"></i>
          <% end %>
        </li>
        <li>
          <%= link_to "https://twitter.com/jack_esss", target: "_blank" do %>
            <i class="fa fa-twitter fa-3x"></i>
          <% end %>
        </li>

      </ul>
      <div class="spacer"></div>
      <div class="col-md-12">
        <p class="copyright text-center">&copy; 2016 by <a target="_blank">Jack Schuss</a>. All Rights Reserved.
        </p>
      </div>



    </div>
  </div>
</section>

app/views/grayscales/_download.html.erb
<section id="download" class="content-section content-section-download text-center">
    <div class="download-section">
        <div class="container">
            <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="portfolio-text">
                    <h1>Portfolio</h1>
                    <p>Here are some of the projects I've worked on recently. All source code can be found on my <a href="http://www.github.com/yakschuss">Github.</a></p>
                </div>
            </div>
        </div>
            <div class="row">
                <h6>
                    projects made with:
                </h6>
                <i class="devicon-ruby-plain devicon-icon-style"></i>
                <i class="devicon-rails-plain devicon-icon-style"></i>
                <i class="devicon-javascript-plain devicon-icon-style"></i>
                <i class="devicon-jquery-plain devicon-icon-style"></i>
                <i class="devicon-angularjs-plain devicon-icon-style"></i>
            </div>
        </div>
    </div>
</section>

app/views/grayscales/_footer.html.erb
<footer>
    <div class="container text-center">
    </div>
</footer>

app/views/grayscales/_form.html.erb
<section id="form-section">
  <div class="container">
    <div class="row">
      <div class="contact-form">
        <div class="form-group">
          <%= form_for :contact_form, url: create_path, name: "contact-form" do |f| %>
            <%= f.text_field :name, placeholder: "Name", class: "form-control name", required: true %>
            </br>

            <%= f.email_field :email, placeholder: "Email", class: "form-control email", required: true %>
            </br>
            <%= f.text_area :message, placeholder: "Message", class: "form-control body", required: true %>
            </br>
            <%= f.submit "Send", class: "btn btn-success" %>
        </div>
      <% end %>
      </div>
    </div>
    </section>

app/views/grayscales/_header.html.erb
<header class="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 header-text">
                    <h3>
                        <b>Hi! My name is Jack.</b>
                    </h3>
                    <p class="intro-text"><br></p>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/grayscales/_map.html.erb
<div id="map">
  <%= render 'contact_form/form' %>
</div>

app/views/grayscales/_navigation.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
        <a class="navbar-brand page-scroll" href="#page-top" id="navbar-brand-header">
            <div class="picture-header">
                <i class="white-logo-picture"></i>
            </div>
            <div class="name-header">
                <span class="light">  Jack</span> Schuss
            </div>
        </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a class="page-scroll" href="/blog">Blog</a>
                </li>
                <li>
                    <a class="page-scroll" href="#about">About</a>
                </li>
                <li>
                    <a class="page-scroll" href="#download">Portfolio</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contact</a>
                </li>
                <!-- <li> -->
                <!--   <%# link_to "Blog", buttercms_blog_path, class: "page&#45;scroll" %> -->
                <!-- </li> -->
                <!--  -->
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/grayscales/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/grayscales/index.html.erb
<%= render 'shim' %>
<%= render 'navigation' %>
<%= render 'header' %>
<%= render 'about' %>
<%= render 'download' %>
<%= render 'projects' %>
<%= render 'contact' %>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PortfolioSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jack Schuss</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag 'dashboard/manifest.css', media: 'all' %>
    <%= javascript_include_tag 'dashboard/manifest.js' %>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

    <%= yield %>

  </body>
</html>

app/views/layouts/grayscale.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if Rails.env == "production"  %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-75142485-1']);
    _gaq.push(['_trackPageview']);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <% end %>
  <title>Jack Schuss</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag 'grayscale/manifest.css', media: 'all' %>
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/master/devicon.min.css">
  <%= javascript_include_tag 'grayscale/manifest.js' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<div class="blog-index">
  <div class="blog-title">
    <h2 class="header">Jack Schuss - Musings</h2>
  </div>



  <div class="posts-div">
    <ul class="post-list">
      <% @posts.each do |post| %>
        <li class="rename-color" style="color:black;">
          <%="#{post.created_at.strftime("%b %d '%y")} "%> <%= link_to " #{post.title}", post_path(post), class: "post-title" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/posts/show.html.erb
<div class="posts-show">
  <div class="container">
    <h2><%= @post.title %></h2>
    <h4><%= @post.body %></h4>
  </div>
</div>